// <auto-generated />
using ContactServiceApp.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactServiceApp.Migrations
{
    [DbContext(typeof(EpsilonDbContext))]
    [Migration("20250328085741_InitialContactTableSetUp")]
    partial class InitialContactTableSetUp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContactServiceApp.Models.Contact", b =>
                {
                    b.Property<long>("MobileNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("mobile_number");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MobileNumber"));

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("MobileNumber");

                    b.ToTable("contacts", (string)null);

                    b.HasData(
                        new
                        {
                            MobileNumber = 9090909090L,
                            EmailId = "anil@gmail.com",
                            Location = "Bangalore",
                            Name = "Anil"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
